services:
  - type: web
    name: n8n
    env: docker
    plan: starter  # or 'standard' for production workloads
    autoDeploy: true
    dockerfilePath: ./Dockerfile  # Optional, if you're using your own Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        value: zeeshan114
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Nissar11
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: '5678'
      - key: WEBHOOK_URL
        value: https://your-subdomain.onrender.com/
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: NODE_ENV
        value: production
      - key: N8N_LOG_LEVEL
        value: info
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_DATABASE
        value: /data/database.sqlite

    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1

